name: snack_example
description: An example of the `snack` package
version: 1.0.0
homepage: https://github.com/arnemolland/snack

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  snack:
    path: ../
