name: snack_example
description: An example of the `snack` package
version: 2.0.0
homepage: https://github.com/arnemolland/snack
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  snack:
    path: ../
