name: snack
description: A SnackBar extension for easier access
version: 1.0.0
homepage: https://github.com/arnemolland/snack

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
