name: snack
description: A SnackBar extension for easier access
version: 1.0.1
homepage: https://github.com/arnemolland/snack

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
