name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Run analyzer
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Setup credentials
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1613554595622
          }
          EOF
      - name: Publish packages
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        run: pub publish -f
